FROM node:20-alpine

WORKDIR '/app'

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ADD . .

RUN npm install

ENV NODE_ENV=development

EXPOSE 3000

ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["npm", "run", "dev"]
